// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title CertificateStore
/// @notice Stores and verifies certificate hashes on a blockchain.
/// @dev This contract is intentionally simple for local development and learning.
contract CertificateStore {
    struct CertificateRecord {
        string certificateHash;
        address issuer;
        uint256 issuedAt;
        bool exists;
    }

    mapping(string => CertificateRecord) private certificates;

    event CertificateStored(
        string indexed certificateId,
        string certificateHash,
        address indexed issuer,
        uint256 issuedAt
    );

    /// @notice Store a certificate hash for a unique certificate ID.
    /// @param certificateId Unique ID generated by the Django certificate system.
    /// @param certificateHash SHA256 hash generated from certificate data.
    function storeCertificateHash(
        string calldata certificateId,
        string calldata certificateHash
    ) external {
        require(bytes(certificateId).length > 0, "Certificate ID is required");
        require(bytes(certificateHash).length > 0, "Certificate hash is required");
        require(!certificates[certificateId].exists, "Certificate already exists");

        certificates[certificateId] = CertificateRecord({
            certificateHash: certificateHash,
            issuer: msg.sender,
            issuedAt: block.timestamp,
            exists: true
        });

        emit CertificateStored(
            certificateId,
            certificateHash,
            msg.sender,
            block.timestamp
        );
    }

    /// @notice Check if a certificate hash matches the hash stored on-chain.
    /// @param certificateId Unique certificate ID to verify.
    /// @param certificateHash Hash to compare with the stored hash.
    /// @return True when the certificate exists and the hash matches.
    function verifyCertificateHash(
        string calldata certificateId,
        string calldata certificateHash
    ) external view returns (bool) {
        if (!certificates[certificateId].exists) {
            return false;
        }

        return (
            keccak256(bytes(certificates[certificateId].certificateHash)) ==
            keccak256(bytes(certificateHash))
        );
    }

    /// @notice Retrieve stored certificate data.
    /// @param certificateId Unique certificate ID to look up.
    /// @return certificateHash Stored SHA256 hash.
    /// @return issuer Account that stored the hash.
    /// @return issuedAt Block timestamp when the hash was stored.
    /// @return exists True when a record exists for the certificate ID.
    function getCertificate(
        string calldata certificateId
    )
        external
        view
        returns (
            string memory certificateHash,
            address issuer,
            uint256 issuedAt,
            bool exists
        )
    {
        CertificateRecord memory record = certificates[certificateId];

        return (
            record.certificateHash,
            record.issuer,
            record.issuedAt,
            record.exists
        );
    }
}
