# Generated by Django 6.0.5 on 2026-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="certificates/generated/"
            ),
        ),
    ]
