# Generated by Django 6.0.5 on 2026-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
